# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Buhler Cleaning
description: Providing clean cans, garages, and lawns
keywords: "cleaning, small business, sweaty start up"
url: https://www.keithbuhler.com/ 
baseurl: "/cleaning"

google_analytics: 
repo: 
disqus_shortname: 
disqus_site_shortname: 

# Author settings
author:
  name: Dionysius
  job: 
  bio: "Entrepreneur"
  thumb: /images/author.jpg
  email: 
  url: 
  github: 
  twitter: 
  facebook: 
  linkedin: 

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: Services
    title: Services

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
